title: Zhang San「张三」
# title: Sun Changsheng
name: "Zhang San"
author: Zhang San
twitter_username: san_zhang
baseurl: ""
description: Document my learning notes.
profile_url: "https://zhangsan.com"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3
